<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <AssemblyName>LogOClock</AssemblyName>
    <RootNamespace>ProjectTimeTracker.Windows</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\AppIcon.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../ProjectTimeTracker.Core/ProjectTimeTracker.Core.csproj" />
    <ProjectReference Include="../ProjectTimeTracker.Infrastructure/ProjectTimeTracker.Infrastructure.csproj" />
    <PackageReference Include="SQLitePCLRaw.provider.winsqlite3" Version="2.1.11" />
  </ItemGroup>
</Project>
